raw:
  study_area_boundary: "data/raw/boundary/ilaje_lga_boundary.shp"
  dem: "data/raw/dem/ilaje_dem.tif"
  outlet_points: "data/raw/outlets/ilaje_outlets.gpkg"
  lulc: "data/raw/lulc/lulc.tif"
  soils: "data/raw/soils/soils.tif"
  hydrography_reference: "data/raw/hydrography_reference/reference_streams.gpkg"
  lineaments: "data/raw/lineaments_optional/lineaments.gpkg"
  settlements: "data/raw/settlements_optional/settlements.gpkg"
  roads: "data/raw/roads_optional/roads.gpkg"
  population: "data/raw/population_optional/population.tif"

interim:
  study_area_projected: "data/interim/reprojected/ilaje_lga_boundary_projected.gpkg"
  clipped_dem: "data/interim/clipped/dem_clipped.tif"
  projected_dem: "data/interim/reprojected/dem_projected.tif"
  corrected_dem: "data/interim/hydrology/dem_hydro_corrected.tif"
  flow_direction: "data/interim/hydrology/d8_pointer.tif"
  flow_accumulation: "data/interim/hydrology/d8_flow_accumulation_cells.tif"
  stream_raster: "data/interim/hydrology/streams_thresholded.tif"
  strahler_order: "data/interim/hydrology/stream_order_strahler.tif"
  shreve_order: "data/interim/hydrology/stream_order_shreve.tif"
  watershed_raster: "data/interim/hydrology/watershed.tif"
  terrain_dir: "data/interim/terrain"
  aligned_factors_dir: "data/interim/aligned/flood_factors"

processed:
  dashboard_layers_dir: "data/processed/dashboard_layers"
  streams_vector: "data/processed/vectors/stream_network.shp"
  watershed_vector: "data/processed/vectors/watershed.gpkg"
  subbasins_vector: "data/processed/vectors/subbasins.gpkg"
  basin_morphometry_csv: "data/processed/tables/basin_morphometry.csv"
  subbasin_morphometry_csv: "data/processed/tables/subbasin_morphometry.csv"
  lineament_density_raster: "data/processed/rasters/lineament_density.tif"
  lineament_stats_csv: "data/processed/tables/lineament_stats.csv"
  drainage_lineament_intersections: "data/processed/vectors/drainage_lineament_intersections.gpkg"
  distance_to_stream_raster: "data/processed/rasters/distance_to_stream.tif"
  drainage_density_raster: "data/processed/rasters/drainage_density.tif"
  twi_raster: "data/processed/rasters/twi.tif"
  spi_raster: "data/processed/rasters/spi.tif"
  fhi_continuous: "data/processed/rasters/flood_hazard_index_continuous.tif"
  fhi_classified: "data/processed/rasters/flood_hazard_index_classified.tif"
  fhi_zones_vector: "data/processed/vectors/flood_hazard_zones.gpkg"
  hazard_area_summary_csv: "data/processed/tables/hazard_area_summary.csv"
  hazard_subbasin_summary_csv: "data/processed/tables/hazard_subbasin_summary.csv"
  subbasin_priority_csv: "data/processed/tables/subbasin_priority_ranking.csv"
  subbasin_priority_gpkg: "data/processed/vectors/subbasin_priority_ranking.gpkg"

outputs:
  maps_dir: "outputs/maps"
  figures_dir: "outputs/figures"
  charts_dir: "outputs/charts"
  reports_dir: "outputs/reports"
  logs_dir: "outputs/logs"
